leigh = User.new(name: "leighsn")
groceries = List.new(name: "Grocery List")
leigh.list = groceries
banana = Item.new(name: "Banana")
milk = Item.new(name: "Milk")
panda_puffs = Item.new(name: "Panda Puffs")
peanut_butter = Item.new(name: "Peanut Butter")
chocolate = Item.new(name: "Chocolate Bar")
broccoli = Item.new(name: "Broccoli")
